services:
  npm:
    hostname: npm
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /selfhost-data/networking/nginx-proxy-manager/data:/data
      - /selfhost-data/networking/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
    