services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./nginx/ssl:/etc/letsencrypt
    networks:
      - nginx-network

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./certbot/cloudflare.ini:/secrets/cloudflare.ini:ro
      - ./nginx/ssl:/etc/letsencrypt
    command: >
      certonly --dns-cloudflare
      --dns-cloudflare-credentials /secrets/cloudflare.ini
      --dns-cloudflare-propagation-seconds 30
      -d ${CERTBOT_DOMAIN} -d ${CERTBOT_WILDCARD_DOMAIN}
      --non-interactive --agree-tos
      --email ${CERTBOT_EMAIL}
    networks:
      - nginx-network
      
networks:
  nginx-network:
    external: true
