services:
  homarr:
    hostname: homarr
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_DATA_PATH}/homarr/app/data/configs:/app/data/configs
      - ${ROOT_DATA_PATH}/homarr/app/public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "7575"
    networks:
      - nginx-network

  grafana:
    hostname: grafana
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - nginx-network

  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    expose:
      - "8000"
      - "9443"
    networks:
      - nginx-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_DATA_PATH}/portainer/data:/data

volumes:
  grafana-data:

networks:
  nginx-network:
    external: true
