server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ghost.YOUR_DOMAIN;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/errors.conf;
    return 301 https://YOUR_DOMAIN$request_uri;
}
