server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          host: selfhost
          __path__: /var/log/nginx/*.log

  - job_name: authlog
    static_configs:
      - targets:
          - localhost
        labels:
          job: authlog
          host: selfhost
          __path__: /var/log/auth.log

  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: selfhost
          __path__: /var/lib/docker/containers/*/*-json.log
