services:
  blog:
    image: 's3343711/astro-blog'
    hostname: blog
    container_name: blog
    expose:
      - "8080"
    networks:
      - nginx-network
      
networks:
  nginx-network:
    external: true
