services:
  blog:
    image: 's3343711/astro-blog'
    hostname: blog
    container_name: blog
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    expose:
      - "3000"
    networks:
      - nginx-network
      
networks:
  nginx-network:
    external: true
